default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: easy_it_development

test:
  <<: *default
  database: easy_it_test

production:
  <<: *default
  database: easy_it_production
  username: easy_it
  password: <%= ENV['EASY_IT_DATABASE_PASSWORD'] %>